version: '3.8'

services:
  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgresql://admin:secret@postgres:5432/rewarddb?sslmode=disable",
      "up"
    ]
    volumes:
      - ./internal/infrastructure/db/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://admin:secret@postgres:5432/rewarddb?sslmode=disable
      - REDIS_ADDR=redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GIN_MODE=release
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rewarddb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "rewarddb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: