name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: rewarddb
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin -d rewarddb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    env:
      DATABASE_URL: postgresql://admin:secret@localhost:5432/rewarddb?sslmode=disable
      REDIS_ADDR: localhost:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -U admin -d rewarddb && break
            sleep 2
          done

      - name: Run DB migrations
        run: |
          migrate -path internal/infrastructure/db/migrations -database "$DATABASE_URL" up

      - name: Download Go modules
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build app
        run: go build -o reward-system ./cmd